### ISSUE TITLE
爆新地、ミツバチの巣ブロックからの蜂の出現の抑制

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/Bakushinchi#3]
あまり時間がなかったので詳しい出現のタイミングはわからんけど一応置いとく

**Comment by book000** [comment]
再現性がありません…。養蜂箱から蜂が出てくるなどのソースはありますか？またサーバ内で再現できますか？

**Comment by kohonayoshi** [comment]
kuruに聞いてください
