### ISSUE TITLE
爆新地、区画分けの道部分の上においたブロックの設置ログが残ってない

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/Bakushinchi#4]
![image](https://user-images.githubusercontent.com/52349485/114295737-23de7500-9ae2-11eb-8bef-a83cde745dc8.png)
直後に砂利がスポンジで拭き取ったので水は消えてしまったすまん

**Comment by kohonayoshi** [comment]
さっきのマグマ水設置荒らしをrbしたら道の上の水だけ残った
水の設置ログは無かった

**Comment by book000** [comment]
再現性あるか確かめて欲しいかも、制限するにしても手のつけようがない

**Comment by kohonayoshi** [comment]
ハーフブロックの上に水を置いてもログが残らない(リマインダー)

**Comment by book000** [comment]
忘れてました ❤️
